### ISSUE TITLE
Error in BootStrapping

### ISSUE THREAD

**Issue by AlexanderSjoholm** [cgraumann/umeyama-matlab#1]
As pointed out at by JDries at http://www.mathworks.com/matlabcentral/fileexchange/49369-cgraumann-umeyama-matlab
there is an error in the section called bootstrapping, when calculating the translation. 
The existing:
`t = mean_Y - R*mean_X;`
should be:
`t = mean_X - R*mean_Y;`

A simple 2 + 2 point set can verify this.

**Comment by cgraumann** [comment]
Just for the sake of complete documentation:
This issue has already been solved in commit 2928d1b.

Thanks for submitting the issue - I have overlooked it otherwise I would have closed it earlier myself.
